export type MonthlyHousingInventoryDataPoint = [
  string, // "month_date_yyyymm" -- 0,
  string, // "country" -- 1,
  string, // "median_listing_price" -- 2,
  string, // "median_listing_price_mm" -- 3,
  string, // "median_listing_price_yy" -- 4,
  string, // "active_listing_count" -- 5,
  string, // "active_listing_count_mm" -- 6,
  string, // "active_listing_count_yy" -- 7,
  string, // "median_days_on_market" -- 8,
  string, // "median_days_on_market_mm" -- 9,
  string, // "median_days_on_market_yy" -- 10,
  string, // "new_listing_count" -- 11,
  string, // "new_listing_count_mm" -- 12,
  string, // "new_listing_count_yy" -- 13,
  string, // "price_increased_count" -- 14,
  string, // "price_increased_count_mm" -- 15,
  string, // "price_increased_count_yy",
  string, // "price_reduced_count",
  string, // "price_reduced_count_mm",
  string, // "price_reduced_count_yy",
  string, // "pending_listing_count",
  string, // "pending_listing_count_mm",
  string, // "pending_listing_count_yy",
  string, // "median_listing_price_per_square_foot",
  string, // "median_listing_price_per_square_foot_mm",
  string, // "median_listing_price_per_square_foot_yy",
  string, // "median_square_feet",
  string, // "median_square_feet_mm",
  string, // "median_square_feet_yy",
  string, // "average_listing_price",
  string, // "average_listing_price_mm",
  string, // "average_listing_price_yy",
  string, // "total_listing_count",
  string, // "total_listing_count_mm",
  string, // "total_listing_count_yy",
  string, // "pending_ratio",
  string, // "pending_ratio_mm",
  string, // "pending_ratio_yy",
  string // "quality_flag"
];
