// Next
import type { NextPage } from "next";
import Head from "next/head";

// Data
import { getMedianListingPriceYYData } from "../data/housingDataMethods";
import { createChartData } from "../data/housingDataMethods";

// Highcharts
import React from "react";
import Highcharts, { chart } from "highcharts/highstock";
import HighchartsReact from "highcharts-react-official";
import HighchartsExporting from "highcharts/modules/exporting";

// if (typeof Highcharts === "object") {
//   console.log("highcharts", Highcharts);
//   HighchartsExporting(Highcharts);
// }

interface IProps {
  chartOptions: any;
}

const Home: NextPage<IProps> = ({ chartOptions }) => {
  console.log(chartOptions);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto min-h-screen p-4">
        <h1 className="text-center text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          US Housing Data
        </h1>
        <div>
          <HighchartsReact
            highcharts={Highcharts}
            constructorType={"stockChart"}
            options={chartOptions}
          />
        </div>
      </main>
    </>
  );
};

export default Home;

export const getStaticProps = async () => {
  const medianListingPriceData = getMedianListingPriceYYData();
  const chartOptions = createChartData(medianListingPriceData);

  return {
    props: { chartOptions },
  };
};
