// Next
import type { NextPage } from "next";
import Head from "next/head";

// Data
import { formatInventoryData } from "../data/housingDataMethods";
import { housingInventory } from "../data/housingData";

// Highcharts
import React from "react";
import Highcharts, { chart } from "highcharts/highstock";
import HighchartsReact from "highcharts-react-official";
import HighchartsExporting from "highcharts/modules/exporting";

// if (typeof Highcharts === "object") {
//   console.log("highcharts", Highcharts);
//   HighchartsExporting(Highcharts);
// }

interface IProps {
  medianListingCountYY: number[][];
  medianListingPriceYY: number[][];
  medianDaysOnMarketByDay: number[][];
  medianDaysOnMarketAsPct: number[][];
}

const Home: NextPage<IProps> = ({
  medianListingPriceYY,
  medianListingCountYY,
  medianDaysOnMarketByDay,
  medianDaysOnMarketAsPct,
}) => {
  const generateWeeklyInventoryChartOptions = () => {
    return {
      title: {
        text: "Housing Inventory Data",
      },
      legend: {
        align: "left",
        verticalAlign: "top",
      },
      yAxis: [
        {
          opposite: false,
          labels: {
            format: "{value} %",
          },
          title: {
            text: "% Change (Y/Y)",
          },
        },
        {
          title: {
            text: "Days Change (Y/Y)",
          },
          labels: {
            format: "{value} days",
          },
        },
      ],

      xAxis: {
        accessibility: {
          rangeDescription: "Range: 2010 to 2020",
        },
      },

      rangeSelector: {
        selected: 1,
      },

      responsive: {
        rules: [
          {
            condition: {
              maxWidth: 500,
            },
            chartOptions: {
              legend: {
                layout: "horizontal",
                align: "center",
                verticalAlign: "bottom",
              },
            },
          },
        ],
      },
      tooltip: {
        shared: true,
      },

      series: [
        {
          name: "Median Listing Price",
          data: medianListingPriceYY,
          yAxis: 0,
          showInNavigator: true,
          tooltip: {
            valueSuffix: " %",
          },
        },
        {
          name: "Median Listing Count",
          data: medianListingCountYY,
          yAxis: 0,
          showInNavigator: true,
          tooltip: {
            valueSuffix: " %",
          },
        },
        {
          name: "Median Days On Market",
          data: medianDaysOnMarketByDay,
          showInNavigator: true,
          yAxis: 1,
          tooltip: {
            valueSuffix: " Days",
          },
        },
        {
          name: "Median Days On Market",
          data: medianDaysOnMarketAsPct,
          showInNavigator: true,
          yAxis: 0,
          tooltip: {
            valueSuffix: " %",
          },
        },
      ],
    };
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto min-h-screen p-4">
        <h1 className="text-center text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          US Housing Data
        </h1>
        <div>
          <HighchartsReact
            highcharts={Highcharts}
            constructorType={"stockChart"}
            options={generateWeeklyInventoryChartOptions()}
          />
        </div>
      </main>
    </>
  );
};

export default Home;

export const getStaticProps = async () => {
  const {
    medianDaysOnMarketByDay,
    medianListingCountYY,
    medianListingPriceYY,
    medianDaysOnMarketAsPct,
  } = formatInventoryData(housingInventory);

  return {
    props: {
      medianListingCountYY,
      medianListingPriceYY,
      medianDaysOnMarketByDay,
      medianDaysOnMarketAsPct,
    },
  };
};
