// Next
import type { NextPage } from "next";
import Head from "next/head";

// axios
import axios from "axios";

// csv-parse
import { parse } from "csv-parse/sync";

// Data
import { formatMonthlyInventoryData } from "../data/housingDataMethods";

// Components
import MonthlyInventoryChart from "../components/charts/MonthlyInventoryChart";

interface IProps {
  monthlyData: {
    dateData: string[];
    listingPriceData: number[];
    daysOnMarketData: number[];
    newListingCountData: number[];
    priceIncreasedCountData: number[];
    priceReducedCountData: number[];
    squareFeetData: number[];
    totalListingCountData: number[];
  };
}

const Home: NextPage<IProps> = ({ monthlyData }) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto min-h-screen p-4">
        <h1 className="text-center text-5xl font-extrabold leading-normal text-white md:text-[5rem]">
          US Housing Data
        </h1>
        <section className="mb-16">
          <h2 className="mb-2 text-center text-2xl text-white">
            Monthly Inventory Data - US
          </h2>
          <MonthlyInventoryChart monthlyData={monthlyData} />
        </section>
      </main>
    </>
  );
};

export default Home;

export const getStaticProps = async () => {
  const { data } = await axios.get(
    "https://econdata.s3-us-west-2.amazonaws.com/Reports/Core/RDC_Inventory_Core_Metrics_Country_History.csv"
  );
  const formattedData = parse(data);
  const monthlyData = formatMonthlyInventoryData(formattedData);

  return {
    props: {
      monthlyData,
    },
  };
};
